name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: tutkowskim/the-voice

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set image tag
        id: vars
        run: echo "tag=$(date "+%Y.%m.%d.%H%M")" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}
            ${{ env.IMAGE_NAME }}:latest

      - name: Trigger update in HomeLab
        run: |
          curl -X POST https://api.github.com/repos/tutkowskim/HomeLab/dispatches \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -d "$(jq -n \
              --arg event_type "update-docker-tag" \
              --arg image_name "${{ env.IMAGE_NAME }}" \
              --arg new_tag "${{ steps.vars.outputs.tag }}" \
              '{event_type: $event_type, client_payload: {image_name: $image_name, new_tag: $new_tag}}')"