name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker-publish.yml'
      - Dockerfile
      - '**/*.java'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: tutkowskim/the-voice

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: echo "tag=$(date "+%Y.%m.%d.%H%M")" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}
            ${{ env.IMAGE_NAME }}:latest

      - name: Trigger Tag Update in Another Repo
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            await octokit.rest.repos.createDispatchEvent({
              owner: 'tutkowskim',
              repo: 'HomeLab',
              event_type: 'update-docker-tag',
              client_payload: {
                new_tag: '${{ steps.vars.outputs.tag }}',
                image_name: '${{ env.IMAGE_NAME }}'
              }
            });